---
- name: display some basic facts
  hosts: web
  tasks:

    - name: Show some properties of {{ inventory_hostname }}
      debug:
        msg: >
          My FQDN is {{ ansible_facts['fqdn'] }}
          and my defaullt IP address is {{ ansible_facts['default_ipv4']['address'] }}
