---
- name: Managing variables
  hosts: server2
  vars:
    web_pkg: httpd
    firewall_pkg: firewalld
    web_service: httpd
    firewall_service: firewalld
    python_pkg: python3-PyMySQL
    rule: http
  tasks:
    - name: Install Packages
      yum:
        name:
          -  "{{ web_pkg }}"
          - "{{ firewall_pkg }}"
          - "{{ python_pkg }}"
        state: latest
    - name: The {{ firewall_service }} service is started and enabled
      service:
        name: "{{ firewall_service }}"
        state: started
        enabled: yes
    - name: The {{ web_service }} service is started and enabled
      service:
        name: "{{ web_service }}"
        state: started
        enabled: true
    - name: Add content to /var/www/html/index.html
      copy:
        content: "Example web content\n"
        dest: /var/www/html/index.html
    - name: The firewall port for {{ rule }} is open
      firewalld:
       service: "{{ rule }}"
       permanent: true
       immediate: true
       state: enabled

- name: Check Connectivity of Web Server on server2
  hosts: localhost
  become: false
  tasks:
    - name: Verify the Apache service
      uri:
        url: http://server2
        status_code: 200
      register: output
    - name: show the content of the captured output
      debug:
        var: output

