---
- name: Set default selinux file context
  hosts: all
  vars:
    path: /home/devops/users.txt
  tasks:
    
    - name: SELinux file context is set to defaults
      file:
        path: "{{ path }}"
        seuser: _default
        serole: _default
        setype: _default
        selevel: _default

